### ISSUE TITLE
reset_prop example isn't working

### ISSUE THREAD

**Issue by pxToolshed** [hyperdiv/hyperdiv-docs#7]
https://docs.hyperdiv.io/guide/props

The reset_prop example isn't working I think. Since the slider value isn't being reset, the text_input value is not being reset either even if you press the reset button.

![image](https://github.com/hyperdiv/hyperdiv/assets/118192057/85cd9813-fb10-46af-966d-3565856737a5)

A way to fix could probably be to reset_prop the value of the slider, too:

```
slider = hd.slider("Slider")
text_input = hd.text_input(value = slider.value)
reset_button = hd.button("Reset")
if reset_button.clicked:
	slider.reset_prop("value")
	text_input.reset_prop("value")

```

**Comment by mariusnita** [comment]
Hi, I need to improve this part of the documentation for clarity.

That part of the docs is trying to show that if you type into the text box, the text box value becomes "mutated" and will no longer follow the slider value. But if you click reset, it forgets its mutated value and starts following the slider value again.


https://github.com/hyperdiv/hyperdiv-docs/assets/5980501/c9d37aa3-fdf3-4235-a90a-dc3e4e47232a

**Comment by pxToolshed** [comment]
oohh! Thanks for the explanation, now I get it. You want me to close the issue since this isn't really an error? 

(sorry, new to the whole github thing, I'm not sure what the agreed upon etiquette is in such cases)

**Comment by mariusnita** [comment]
Thanks! Yeah I'll close it.

But noted that that part of the documentation needs to be clearer.
